---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    name: springboot
  name: spring-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: asifaan/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080      

# Node Port Service
kind: Service
apiVersion: apps/v1
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot

# Mongo host path rc
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup

# Mongo Node Port RC
kind: Service
apiVersion: apps/v1
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
